spring.application.name=generic_dpp_platform

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/dpp_generic_java}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}

platform.platform-name=${PLATFORM_NAME:DPP Generic Java}
platform.base-url=${BASE_URL:https://generic-java-dpp.bfh.ch}
platform.issuer-id=${ISSUER_ID:issuerA}
platform.resolver-base-url=${RESOLVER_BASE_URL:http://localhost:8080}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
spring.flyway.validate-migration-naming=true

spring.jpa.hibernate.ddl-auto=validate
