CREATE TABLE IF NOT EXISTS subject_type
(
    id          bigserial PRIMARY KEY,
    name        varchar(255) NOT NULL,
    description TEXT,

    CONSTRAINT subject_type_name_unique UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS dpp_schema
(
    major_version   INTEGER                     NOT NULL,
    minor_version   INTEGER                     NOT NULL,
    subject_type_id BIGINT                      NOT NULL,
    schema_document JSONB                       NOT NULL,
    published_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_dpp_schema PRIMARY KEY (major_version, minor_version, subject_type_id),
    CONSTRAINT FK_DPP_SCHEMA_ON_SUBJECT_TYPE FOREIGN KEY (subject_type_id) REFERENCES subject_type (id)
);

CREATE TABLE IF NOT EXISTS platform
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    platform_name  VARCHAR(255)                            NOT NULL,
    abbreviation   VARCHAR(255)                            NOT NULL,
    resolution_url VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_platform PRIMARY KEY (id),
    CONSTRAINT platform_abbreviation_unique UNIQUE (abbreviation)
);

CREATE TABLE IF NOT EXISTS platform_mapping
(
    platform_id     BIGINT NOT NULL,
    subject_type_id BIGINT NOT NULL,
    CONSTRAINT pk_platform_mapping PRIMARY KEY (platform_id, subject_type_id),
    CONSTRAINT FK_PLATFORM_MAPPING_ON_PLATFORM FOREIGN KEY (platform_id) REFERENCES platform (id),
    CONSTRAINT FK_PLATFORM_MAPPING_ON_SUBJECT_TYPE FOREIGN KEY (subject_type_id) REFERENCES subject_type (id)
);
