spring.application.name=generic_dpp_platform

spring.datasource.url=jdbc:postgresql://localhost:5432/dpp_generic_java
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
spring.flyway.validate-migration-naming=true

spring.jpa.hibernate.ddl-auto=validate
