CREATE TABLE IF NOT EXISTS subject_type
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description TEXT,
    CONSTRAINT pk_subject_type PRIMARY KEY (id),
    CONSTRAINT uq_subject_type_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS platform_config
(
    config_key   VARCHAR(255) NOT NULL,
    config_value VARCHAR(255) NOT NULL,
    CONSTRAINT pk_platform_config PRIMARY KEY (config_key)
);

INSERT INTO platform_config (config_key, config_value)
VALUES ('platform_name', 'Generic DPP Platform'),
       ('base_url', 'http://localhost:8081'),
       ('issuer_id', 'gendpp'),
       ('resolver_base_url', 'http://localhost:8080');

CREATE TABLE IF NOT EXISTS dpp_schema
(
    major_version   INTEGER                     NOT NULL,
    minor_version   INTEGER                     NOT NULL,
    subject_type_id BIGINT                      NOT NULL,
    schema_document JSONB                       NOT NULL,
    published_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_dpp_schema PRIMARY KEY (major_version, minor_version, subject_type_id)
);

ALTER TABLE dpp_schema
    ADD CONSTRAINT FK_DPP_SCHEMA_ON_SUBJECT_TYPE FOREIGN KEY (subject_type_id) REFERENCES subject_type (id);
