CREATE TABLE IF NOT EXISTS subject_type
(
    id          bigserial PRIMARY KEY,
    name        varchar(255) NOT NULL,
    description TEXT,

    CONSTRAINT subject_type_name_unique UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS dpp_schema
(
    major_version   INTEGER                     NOT NULL,
    minor_version   INTEGER                     NOT NULL,
    subject_type_id BIGINT                      NOT NULL,
    schema_document JSONB                       NOT NULL,
    published_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_dpp_schema PRIMARY KEY (major_version, minor_version, subject_type_id)
);

ALTER TABLE dpp_schema
    ADD CONSTRAINT FK_DPP_SCHEMA_ON_SUBJECT_TYPE FOREIGN KEY (subject_type_id) REFERENCES subject_type (id);

CREATE TABLE IF NOT EXISTS platform_mapping
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    platform_name   VARCHAR(255)                            NOT NULL,
    subject_type_id BIGINT                                  NOT NULL,
    abbreviation    VARCHAR(255)                            NOT NULL,
    resolution_url  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_platform_mapping PRIMARY KEY (id)
);

ALTER TABLE platform_mapping
    ADD CONSTRAINT FK_PLATFORM_MAPPING_ON_SUBJECT_TYPE FOREIGN KEY (subject_type_id) REFERENCES subject_type (id);